### ISSUE TITLE
Africa

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#1]
- [x]  Chad Basin (Niger, Chad, Nigeria, Algeria, Libya, Sudan, CAR, Cameroon) http://eprints.imdea-agua.org:13000/1192/1/A-Cooperation-for-International-Waters-in-Africa-CIWA-Technical-Report.pdf
- [x] Nubian Aquifer (Chad, Egypt, Libya, Sudan) https://link.springer.com/article/10.1007/s10040-013-1039-3
- [x] Ethiopia https://www-sciencedirect-com.abc.cardiff.ac.uk/science/article/pii/S0022169420306740
- [x] Mali https://link-springer-com.abc.cardiff.ac.uk/content/pdf/10.1007/s00254-008-1646-9.pdf
- [x] Somaliland https://www.acquesotterranee.net/index.php/acque/article/view/018-13-0042/139

**Comment by kbefus** [comment]
The only link that worked for me was the last one. @AndresQuichimbo, you're welcome to try for the other ones. I find the questions on the country of origin rather extra and a potential barrier, although I see the purpose in asking people to record it. I think the link to the report/data is more useful than an option to upload files.

**Comment by rreinecke** [comment]
@kbefus I opened #8 to collect all comments that relate to the current version of the submission from and what we could do to improve it.
