### ISSUE TITLE
change platform to www.soscisurvey.de 

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#10]
- this would improve the overall setup of the questionnaire since we could constrain the format = less work for future sprints in terms of cleaning up data

But on the other hand it is quite some effort and it is intended for fixed periods of time only.
Maybe google form is still the best option...

**Comment by XanderHuggins** [comment]
another idea (if soscisurvey.de is only intended to be used over fixed periods of time) is to develop a survey as an R Shiny App. I have experience building some shiny apps before, so could help here if needed, but also we should probably be sure that google forms can't accomplish what we want before switching over. Here's a neat article on benefits of R shiny apps: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0232424

**Comment by rreinecke** [comment]
sounds good :). In general I'm not a fan of R - just from a computer science perspective I think it is not a good language, but that would be certainly one option to build a longer lasting portal. I think we should talk to Jose and the others that are developing the GroMoPo Portal and ask what they need.
I just opened this issue to document our discussion but I think we need a long term solution that works for everyone and maybe sociscurevey and google are both not the right tools for that.

**Comment by rreinecke** [comment]
We will likely move to python and implement it in the gromopo app.
