### ISSUE TITLE
Asia, Australia

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#2]
# Asia - India
- [x] https://www.researchgate.net/publication/337571441_Groundwater_modeling_of_Musi_basin_Hyderabad_India_a_case_study
- [x] Ganga Basin (Deltares/journal article)
- [x] https://www.prsindia.org/administrator/uploads/general/1455682937~~Overview%20of%20Ground%20Water%20in%20India.pdf
- [x] https://www.researchgate.net/publication/325451776_Numerical_groundwater_flow_modeling_of_Kohat_Basin_An_example_from_Himalayan_fold_and_thrust_belt_Pakistan
- [x] https://link.springer.com/article/10.1007/s40899-015-0002-y
- [x] https://www.pakjas.com.pk/papers/2872.pdf
- [x] https://inis.iaea.org/search/search.aspx?orig_q=RN:49103472
- [x] https://ascelibrary.org/doi/10.1061/%28ASCE%29WR.1943-5452.0000733
- [x] https://academic.oup.com/gji/article/173/1/17/553487

# Asia Russia
- [x] https://link.springer.com/article/10.1007/s40899-015-0002-y

# Japan
- [x] https://www.researchgate.net/publication/290559986_Use_of_groundwater_flow_model_in_the_analysis_of_a_creeping_landslide_in_western_Japan
https://pdf.sciencedirectassets.com/270397/1-s2.0-S1878029612X00045/1-s2.0-S1878029612000539/main.pdf

# Asia other
- [x] https://ui.adsabs.harvard.edu/abs/2015EGUGA..17.8003S/abstract
- [x] https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwji7rDn6JnxAhX-JTQIHZpcAxcQFjAFegQIChAE&url=https%3A%2F%2Fwww.mdpi.com%2F2073-4441%2F13%2F10%2F1395%2Fpdf&usg=AOvVaw0IrI8tQqu7CMca9CGoDE5X
- [x] https://essay.utwente.nl/68510/1/Roover-Sam-de.pdf
- [x] https://jurnal.ugm.ac.id/jag/article/view/39996
- [x] https://www.google.ca/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjqg5_F6ZnxAhX8CTQIHTcgD8UQFjAAegQIAxAD&url=https%3A%2F%2Fwww.researchgate.net%2Fpublication%2F227178602_Assessment_Of_A_Groundwater_Flow_Model_Of_The_Bangkok_Basin_Thailand_Using_Carbon-14-Based_Ages_And_Paleohydrology&usg=AOvVaw1E7_FfM0ylM3naGfznyht0 or https://pubs.er.usgs.gov/publication/70018671
- [x] https://caia.gsd.spc.int/index.php/groundwater-modelling
- [x] https://www.mdpi.com/2073-4441/9/10/788/htm
- [x] https://files.hawaii.gov/dlnr/cwrm/publishedreports/CWRM-1.pdf

# Australia NZ

**Comment by daniel-v-k** [comment]
page not found for:  
https://www.prsindia.org/administrator/uploads/general/1455682937~~Overview%20of%20Ground%20Water%20in%20India.pdf

**Comment by daniel-v-k** [comment]
report not found:  https://caia.gsd.spc.int/index.php/groundwater-modelling
