### ISSUE TITLE
Europe + Salinity models

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#4]
- [x] [Pan-European](https://link-springer-com.abc.cardiff.ac.uk/article/10.1007/s40710-017-0216-0)
- [x] #16
- [x] Island https://skemman.is/bitstream/1946/21739/1/Vaiva%20%C4%8Cypait%C4%97.thesis.pdf
- [ ] Germany, bav: https://www.lfu.bayern.de/wasser/grundwassermodelle/index.htm

**Comment by fedunn** [comment]
I've done Iceland, but can't check it off the list. I saw in another group that I needed to have accepted all the invitations to join, but I thought I had.

**Comment by rreinecke** [comment]
@fedunn should work now. I think someone forgot to also add you to this project.

**Comment by fedunn** [comment]
Done https://www.nature.com/articles/s41597-019-0328-7

**Comment by fedunn** [comment]
'Environment Agency of England and Wales' link seems to be it's own model repository which is very closed, only accessible by Environment Agency staff.

**Comment by dzamrsky** [comment]
Yes i had the same issue when i tried to log in there. Just leave it i would say, we can make a remark in the google document..

**Comment by fedunn** [comment]
'Germany, bav' link is in German, so probably best investigated by someone who speaks German.

**Comment by dzamrsky** [comment]
Yes indeed! If only we had somebody here who speak German.. :D

**Comment by rreinecke** [comment]
:D @daniel-v-k and me will tackle the German models in the next sprint ;)

**Comment by dzamrsky** [comment]
The UK link only provides general information about the models - but no direct information. That would need to be accessed via private institutions or individually (not feasible in this sprint) - so i will just cross it off the list for now. 

@rreinecke could you have a look at the Bavarian model (or ask Daniel K. to do it), since our German is not very gut! thanks :)

In the meantime we got some additional links from Gu (Deltares), so me and Frances will be filling those in,

**Comment by rreinecke** [comment]
> The UK link only provides general information about the models - but no direct information. That would need to be accessed via private institutions or individually (not feasible in this sprint) - so i will just cross it off the list for now.
> 
> @rreinecke could you have a look at the Bavarian model (or ask Daniel K. to do it), since our German is not very gut! thanks :)
> 
> In the meantime we got some additional links from Gu (Deltares), so me and Frances will be filling those in,

@daniel-v-k
