### ISSUE TITLE
North America

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#5]
# USA
- [x] USGS gw model web app https://webapps.usgs.gov/gwwebflow/?tds_url=https%3A%2F%2Ftxthredds.usgs.gov%2F&tds_dir=public%2Fgwwebflow%2Fviewer%2F
- [ ] USGS RASA models https://water.usgs.gov/ogw/rasa/html/introduction.html
- [x] #9
- [ ] USGS NJ models https://www.usgs.gov/centers/nj-water/science/program-maintain-and-update-groundwater-models?qt-science_center_objects=0#qt-science_center_objects
- [ ] USGS UT models https://www.usgs.gov/centers/ut-water/science/groundwater-models?qt-science_center_objects=3#qt-science_center_objects
- [ ] Texas: GAM
- [x] Kansas https://agriculture.ks.gov/divisions-programs/dwr/managing-kansas-water-resources/information-about-kansas-water-resources/hydrologic-models 
- [x] Nebraska: https://www.usgs.gov/centers/ne-water/science/elkhorn-loup-model?qt-science_center_objects=0#qt-science_center_objects
- [ ] Western USA (AZ, CA, CO, ID, KS, NE, TX) Table S1 from Rossman & Zlotnik (2013)  https://static-content.springer.com/esm/art%3A10.1007%2Fs10040-013-1010-3/MediaObjects/10040_2013_1010_MOESM1_ESM.pdf
- [x] Wisconsin: http://onlinelibrary.wiley.com/doi/10.1111/j.1745-6584.2007.00427.x/abstract
- [x] Wis. http://pubs.er.usgs.gov/publication/sir20155162
- [x] Wis http://onlinelibrary.wiley.com/doi/10.1111/gwat.12536/abstract
- [ ] Wis. https://dnr.wisconsin.gov/topic/Wells/HighCap/CSLStudy.html
- [x] Wis. http://pubs.er.usgs.gov/publication/70178358
- [x] Lake Mich. http://onlinelibrary.wiley.com/doi/10.1111/gwat.12389/abstract
- [ ] SD: https://www.usgs.gov/centers/dakota-water/science/groundwater-flow-model-high-plains-aquifer-south-dakota?qt-science_center_objects=0#qt-science_center_objects
- [x] SD: https://pubs.er.usgs.gov/publication/sir20195117
- [x] SD: https://pubs.er.usgs.gov/publication/sir20185137
- [x] SD: https://pubs.usgs.gov/sir/2009/5205/
- [x] SD: https://pubs.er.usgs.gov/publication/wri7563
- [x] Williston: https://pubs.er.usgs.gov/publication/sir20175158

# Other

- [ ] BC https://docs.google.com/document/d/1_Ewqs_J748R-O1RM9lF-ZaR9h9ClqEJCQCBLBhbwEu8/edit?usp=sharing
- [x] Can. https://doi.org/10.1080/07011784.2019.1671235 
- [ ] Que https://www.environnement.gouv.qc.ca/eau/souterraines/programmes/acquisition-connaissance.htm
- [x] https://doi.org/10.4095/288107
- [ ] https://www.oakridgeswater.ca/numerical-modeling

**Comment by XanderHuggins** [comment]
> 
> 
> @XanderHuggins do you wanna help out with this one? Can't remember which region you were assign to in the meeting on Friday.

sounds great!

**Comment by ChinchuMohan** [comment]
> # USA
> * [ ]  USGS gw model web app https://webapps.usgs.gov/gwwebflow/?tds_url=https%3A%2F%2Ftxthredds.usgs.gov%2F&tds_dir=public%2Fgwwebflow%2Fviewer%2F
> * [ ]  USGS RASA models https://water.usgs.gov/ogw/rasa/html/introduction.html
> * [x]  [Ozark aquifer https://www.sciencebase.gov/catalog/item/5a983034e4b06990606ddba7 #9](https://github.com/Gromopo/GroMoPo_DataCollection/issues/9)
> * [ ]  USGS NJ models https://www.usgs.gov/centers/nj-water/science/program-maintain-and-update-groundwater-models?qt-science_center_objects=0#qt-science_center_objects
> * [ ]  USGS UT models https://www.usgs.gov/centers/ut-water/science/groundwater-models?qt-science_center_objects=3#qt-science_center_objects
> * [ ]  Texas: GAM
> * [ ]  Kansas https://agriculture.ks.gov/divisions-programs/dwr/managing-kansas-water-resources/information-about-kansas-water-resources/hydrologic-models
> * [ ]  Nebraska: https://www.usgs.gov/centers/ne-water/science/elkhorn-loup-model?qt-science_center_objects=0#qt-science_center_objects
> * [ ]  Western USA (AZ, CA, CO, ID, KS, NE, TX) Table S1 from Rossman & Zlotnik (2013)  https://static-content.springer.com/esm/art%3A10.1007%2Fs10040-013-1010-3/MediaObjects/10040_2013_1010_MOESM1_ESM.pdf
> * [ ]  Wisconsin: http://onlinelibrary.wiley.com/doi/10.1111/j.1745-6584.2007.00427.x/abstract
> * [ ]  Wis. http://pubs.er.usgs.gov/publication/sir20155162
> * [ ]  Wis http://onlinelibrary.wiley.com/doi/10.1111/gwat.12536/abstract
> * [ ]  Wis. https://dnr.wisconsin.gov/topic/Wells/HighCap/CSLStudy.html
> * [ ]  Wis. http://pubs.er.usgs.gov/publication/70178358
> * [ ]  Lake Mich. http://onlinelibrary.wiley.com/doi/10.1111/gwat.12389/abstract
> * [ ]  SD: https://www.usgs.gov/centers/dakota-water/science/groundwater-flow-model-high-plains-aquifer-south-dakota?qt-science_center_objects=0#qt-science_center_objects
> * [ ]  SD: https://pubs.er.usgs.gov/publication/sir20195117
> * [ ]  SD: https://pubs.er.usgs.gov/publication/sir20185137
> * [ ]  SD: https://pubs.usgs.gov/sir/2009/5205/
> * [ ]  SD: https://pubs.er.usgs.gov/publication/wri7563
> * [x]  Williston: https://pubs.er.usgs.gov/publication/sir20175158
> 
> # Other
> * [ ]  BC https://docs.google.com/document/d/1_Ewqs_J748R-O1RM9lF-ZaR9h9ClqEJCQCBLBhbwEu8/edit?usp=sharing
> * [x]  Can. https://doi.org/10.1080/07011784.2019.1671235
> * [ ]  Que https://www.environnement.gouv.qc.ca/eau/souterraines/programmes/acquisition-connaissance.htm
> * [x]  https://doi.org/10.4095/288107
> * [ ]  https://www.oakridgeswater.ca/numerical-modeling

**Comment by rreinecke** [comment]
@ChinchuMohan you can click on the boxen in my post or do you want to add other links that are not already in this issue?

**Comment by ChinchuMohan** [comment]
@rreinecke I tried to click the box in your post but it is inactive for me

**Comment by sruzzante** [comment]
Chinchu, I had the same problem. You have to accept both invites from
Robert (the GroMoPo invite and the invite to the GroMoPo_DataCollection.

Sacha

**Comment by ChinchuMohan** [comment]
@sruzzante Thanks a lot it is working now :)
