### ISSUE TITLE
Modify google form

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#6]
Modify form as discussed in meeting.

- [x] Change scales

**Comment by dzamrsky** [comment]
Hi Robert, I still cant access the form for some reason.. During the meeting there were a few suggestions:
- the model layer number can be bit confusing - it would help to change the ranges to 2-5, 6-10, 11-15, 16-25 etc.
- the question about model developer being from the same country - rephrase to "Is the model developer's institute located in the same country as the model location"
- put (optional, don't spend time looking for it if not easily available) into the part where we ask to upload the shapefile, to prevent people from loosing time looking for shapefiles

thanks! Daniel

**Comment by rreinecke** [comment]
@dzamrsky will do.

**Comment by rreinecke** [comment]
Done.
