### ISSUE TITLE
Further improvements submission form

### ISSUE THREAD

**Issue by rreinecke** [Gromopo/GroMoPo_DataCollection#8]
This issue collects all notes on the current submission form. Feel free to comment.

Tasks to improve the form:

- [x] Improve ordering of questions to reduce scrolling
- [x] Add a message at the start on how long it takes to fill out the form (for your own and other models)
- [x] Split up remaining models links in the issues in separate issues and tasks if they contain more than one model
- [x] model scale question: change the wording from < 1000km2 to 100 - 1000 km2 etc.
- [x] slider with size? is it possible in the google docs?
- [ ] change the model purpose question - scientific investigation/groundwater resources, provide clearer definitions and maybe examples
- [x] coupling + purpose question - should we reformulate and group answers into larger blocks?
- [x] time period question - we need to change the format on how to fill in the answer - dropdown menus for start and end year? define the format in the title? "fill in start_year - final_year or SS (if steady-state)". Or maybe conditional question where we would ask if it is SS or not, if not then fill in the years.
- [ ] for next sprint (or before) fix the "unsure" entries in geology question - AKA "SWAT team"
- [x] evaluation/calibration question maybe too specific, try to merge them into larger categories
- [x] depth of model - maybe define ranges? to avoid the specific answers.
- [x] #10
- [x] in cases where there are no authors - could be some organizational/consultancy reports - specify the name of the consultancy and their contact information
- [x] Change upload "other" question to a url entry to point to other data - we don't want more than the shapefile. The links could be separated by semicolons to allow connections to metadata, other related reports, and a link to where the model is stored.
- [x] Is the numerical model based on a conceptual model that is illustrated in a publication or report? If necessary, see Enemark et al. 2019 for definition of ‘conceptual model’. Please add this to the list of suggested form changes…

**Comment by dzamrsky** [comment]
Comments from the meeting:
- model scale question: change the wording from < 1000km2 to 100 - 1000 km2 etc. 
- slider with size? is it possible in the google docs?
- change the model purpose question - scientific investigation/groundwater resources, provide clearer definitions and maybe examples
- coupling + purpose question - should we reformulate and group answers into larger blocks?
- time period question - we need to change the format on how to fill in the answer - dropdown menus for start and end year? define the format in the title? "fill in start_year - final_year or SS (if steady-state)". Or maybe conditional question where we would ask if it is SS or not, if not then fill in the years.
- for next sprint (or before) fix the "unsure" entries in geology question - AKA "SWAT team"
- evaluation/calibration question maybe too specific, try to merge them into larger categories
- depth of model - maybe define ranges? to avoid the specific answers.
- change platform to the German polling platform Robert mentioned - this would improve the overall setup of the questionnaire since we could constrain the format = less work for future sprints in terms of cleaning up data
- in cases where there are no authors - could be some organizational/consultancy reports - specify the name of the consultancy and their contact information

**Comment by dzamrsky** [comment]
Split USA into individual repositories for the next sprint. And also revisit the order of the question - maybe we can make it more efficient and reduce scrolling.

**Comment by rreinecke** [comment]
Add message at the start. or your own model: 15min, other model 15-30

**Comment by rreinecke** [comment]
> Split USA into individual repositories for the next sprint. And also revisit the order of the question - maybe we can make it more efficient and reduce scrolling.

@XanderHuggins would you be willing to tackle the separation into issues? I really liked your suggestion!

**Comment by rreinecke** [comment]
@kbefus you made comments in #1 
> I find the questions on the country of origin rather extra and a potential barrier, although I see the purpose in asking people to record it. I think the link to the report/data is more useful than an option to upload files.
and here:

> I don't think the form should have a second upload feature for other model data. Instead, I think it is exceedingly important that we have a direct way to point users to the model data - doi is fine, but I think a clickable url that takes them to the data would be a most useful feature. For items with a doi, this would be easy, but some models are stored elsewhere. The USGS models that I uploaded and are in the working example popups show the links, although I hadn't figured out the java required to make them hyperlinks. I built the popups after two USGS interactive maps (CA and WA), which are even more interactive than ours (populate a list in a side column depending on field of view) - I don't think this is a needed feature.

Could you provide short propositions on how to fix these things? So I can add them to the task list in this issue. I'm not 100% sure of what you would like to change.

**Comment by kbefus** [comment]
I think the upload "other" question should be changed to a url entry to point to other data - we don't want more than the shapefile. The links could be separated by semicolons to allow connections to metadata, other related reports, and a link to where the model is stored.

**Comment by rreinecke** [comment]
adding Juans mail here for further discussion. I think this would be a great replacement for #10

> Hi All,
> 
>  
> 
> After going through the doc it seems that one of the key issues going forward is rethinking how model data is collected and then integrated into the GroMoPo platform.
> 
>  
> 
> Streamlit has very recently introduced features that can be used to create forms directly in the app:
> 
>  
> 
> https://www.youtube.com/watch?v=RHzjE-WBaSk
> 
>  
> 
> I think that building the form into the dashboard is a no brainer, since the data collection step would be hosted in the app itself as opposed to dealing with the limitations of Google Forms and the extra step of reading the data into Python. The form would sit as a separate page in the Streamlit app and once the user submits the form we could automatically process the data, runs checks, send the form out for review/approval, load into the map, etc.
> 
>  
> 
> If everyone agrees I’d be happy to push a MWE of the form to the repository. That would also enable us to work on the framing/intent of each question and the user experience directly on the platform code. We could even add a timer to automatically keep track of how long people take to fill out the form!
> 
>  
> 
> I can also have a crack at loading the ~80 models from the sprint to the map but for this we will need at least UTM point coordinates for each model (to create a placemark on the map). Ideally, we would like to load a shapefile with the model boundaries, but we can leave that for later.
> 
>  
> 
> Happy to discuss
> 
>  
> 
> Regards
> 
> Juan

**Comment by kbefus** [comment]
- [ ]  bounding box coordinate entry rather than centroid? two extra values lead to more insightful entry and is a fairly standard request

**Comment by rreinecke** [comment]
@dzamrsky could you check if we tick all boxes and can close this for now? I agree that entering a bounding box directly is a good idea.

**Comment by rreinecke** [comment]
- [ ] The model source link should be mandatory (?) -> but what if the paper is very old?

**Comment by rreinecke** [comment]
> @dzamrsky could you check if we tick all boxes and can close this for now? I agree that entering a bounding box directly is a good idea.

@dzamrsky what do you think?

**Comment by dzamrsky** [comment]
Sorry to react late on this. I think we can close this for now, except that we did not address the missing geology "SWAT" team. But i think we can maybe keep that in mind for feedback after this current sprint?
Bounding box sounds good - i will change the google form now before people start filling it in!
